# Generated by Django 4.1.2 on 2022-12-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile_profile_cardnum_profile_profile_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_cardnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_sec_code',
            field=models.IntegerField(default=123),
        ),
    ]
